# Generated by Django 5.2.9 on 2025-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default='exit', upload_to='products/'),
            preserve_default=False,
        ),
    ]
